version: '3.8'

networks:
  nexusenergy-net:
    driver: bridge

services:
  nexusenergy-mysql:
    image: mysql:latest
    container_name: nexusenergy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./arquivos_sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - nexusenergy-net

  nexusenergy-node:
    build:
      context: .
      dockerfile: dockerFile_node
    container_name: nexusenergy-node
    ports:
      - "80:80"
    networks:
      - nexusenergy-net

  nexusenergy-java:
    build:
      context: .
      dockerfile: dockerFile_java  
    container_name: nexusenergy-java
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    networks:
      - nexusenergy-net
    ports:
      - "8080:8080"


