version: '3.8'

networks:
  nexusenergy-net:  
    name: nexusenergy-net
    driver: bridge
    attachable: true

services:
  nexusenergy-mysql:
    image: mysql:latest
    container_name: nexusenergy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Vidanova-123
    volumes:
      - ./arquivos_sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - nexusenergy-net


  nexusenergy-node:
    build:
      context: .
      dockerfile: dockerFile_node
    container_name: nexusenergy-node
    ports:
      - "80:80"
    networks:
      - nexusenergy-net


