# Baixa a imagem com Java mais recente
FROM openjdk:latest

# Instala o git
RUN apt-get update && apt-get install -y git

# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Clona o repositório do seu projeto
RUN git clone https://github.com/NexusEnergyy/PrototipoJAR.git .

# Muda o diretório para a pasta PrototipoJar
WORKDIR /usr/src/app/PrototipoJar

# Executa o Arquivo Jar
CMD ["java", "-jar", "PrototipoJar.jar"]