# Use a imagem mais leve do OpenJDK 21
FROM openjdk:21-slim

# Instala o Git no container
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Clona o repositório do seu projeto
RUN git clone https://github.com/NexusEnergyy/PrototipoJAR.git .

# Muda o diretório para a pasta PrototipoJar
WORKDIR /usr/src/app/PrototipoJar

# Comando para executar o arquivo JAR
CMD ["java", "-jar", "PrototipoJar.jar"]
